// src/application/use_cases/consent_event/log.ts
import { ConsentEvent } from "../../../domain/consent_event";
import type { IConsentEventRepository } from "../../../domain/repositories/IConsentEventRepository";
import { v4 as uuidv4 } from "uuid";

export default async function logConsentEvent(
  orgId: string,
  userId: string,
  categories: Record<string, any>,
  userAgent: string | null,
  ipAddress: string | null,
  eventType: 'accept' | 'reject' | 'update',
  { consentEventRepository }: { consentEventRepository: IConsentEventRepository }
): Promise<ConsentEvent> {
  const event = new ConsentEvent(
    null, // id will be generated by MongoDB
    orgId,
    userId,
    categories,
    new Date(),
    userAgent,
    ipAddress,
    eventType
  );
  return consentEventRepository.logEvent(event);
}
