version: "3"
services:
  postgres:
    image: postgres:15
    container_name: consentlayer_db
    restart: always
    env_file:
      - ../packages/api/.env
    environment:
      # POSTGRES_USER: ${DB_USER}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_DB: ${DB_NAME}
      - POSTGRES_USER=consentlayer
      - POSTGRES_PASSWORD=consentlayer_ps
      - POSTGRES_DB=consentlayer_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: consentlayerMongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
